name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Store Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

      - name: Setup Hosts
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan -p 57242 vps.trelta.dev >> ~/.ssh/known_hosts          

      - name: Deploy
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -p 57242 -J server@vps.trelta.dev:57242 server@10.8.0.2 << 'EOF'
            cd /srv/trelbot
            git pull origin production
            sudo systemctl restart trelbot
          EOF
        env:
          SSH_COMMAND: ${{ vars.SSH_COMMAND }}
