name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Jump Host
        run: |
          mkdir -p ~/.ssh
          cat $SSH_CONFIG > ~/.ssh/config
          chmod 600 ~/.ssh/config          

      - name: Deploy
        run: |
          $SSH_COMMAND << 'EOF'
            cd /srv/trelbot
            git pull origin production
            systemctl restart trelbot
          EOF
        env:
          SSH_COMMAND: ${{ vars.SSH_COMMAND }}
          SSH_CONFIG: ${{ vars.SSH_CONFIG }}_

